[mongodb]
mongodb.devopsbhaskar.fun

[redis]
redis.devopsbhaskar.fun

[mysql]
mysql.devopsbhaskar.fun

[rabbitmq]
rabbitmq.devopsbhaskar.fun

[catalogue]
catalogue.devopsbhaskar.fun

[cart]
cart.devopsbhaskar.fun

[user]
user.devopsbhaskar.fun

[shipping]
shipping.devopsbhaskar.fun

[payment]
payment.devopsbhaskar.fun

[frontend]
frontend.devopsbhaskar.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321